### ISSUE TITLE
Include rationale for GCC wrapping LLD in the qualification documents

### ISSUE THREAD

**Issue by pietroalbini** [ferrocene/ferrocene#106]
PR #100 switched our targets to use LLD as the linker, and for Linux targets we wrap the invocation through GCC/clang to inject system libraries. We should update the qualification documents to handle this:

```[tasklist]
### Tasks
- [x] We should add our reasoning for why you can use any version of GCC/clang and still maintain qualification.
- [x] We should update the safety manual with the constraints for GCC/clang.
- [x] We should update the user manual with the new state of things.
- [ ] We *might* need to update the graph in the "purpose" chapters, and the list of components in the qualification plan.
```

**Comment by jonathanpallant** [comment]
Some relevant updates in #133

**Comment by pietroalbini** [comment]
Updated the issue with a task list of the items we still need to cover.

**Comment by jonathanpallant** [comment]
> We should add our reasoning for why you can use any version of GCC/clang and still maintain qualification.

Where should we add this @pietroalbini ?

**Comment by pietroalbini** [comment]
Probably in https://public-docs.ferrocene.dev/main/qualification/plan/details.html ?
