### ISSUE TITLE
Investigate `-fix-cortex-a53-843419`

### ISSUE THREAD

**Issue by pietroalbini** [ferrocene/ferrocene#125]
In #123 we discovered that GCC passes the `-fix-cortex-a53-843419` flag to linkers to address an errata in Cortex-A53 processors. This means that by default GCC seems to pass that, but we need to do some work around it:

```[tasklist]
### Tasks
- [ ] Check whether bare LLD also implements the mitigation, or if we need to change the target spec or  mandate users pass `-C link-args` in the safety manual.
- [ ] Include in the safety manual that the mitigation must be enabled.
- [ ] Add a test to ensure the mitigation works.
- [ ] Include detection in FST to require the flag to be passed if CC doesn't include it.
```

**Comment by jonathanpallant** [comment]
1) https://github.com/rust-lang/llvm-project/blob/7738295178045041669876bf32b0543ec8319a5c/lld/ELF/Arch/AArch64.cpp#L400-L408

Our LLD supports the fix.

**Comment by pietroalbini** [comment]
Thankfully yes! Grepping for `fixCortexA53Errata` in the LLD source code though it seems we need to pass that flag for the mitigation to work (as some code is gated on that flag being true). Not sure whether whether we do that, or if somewhere the compiler passes it on its own.

**Comment by jonathanpallant** [comment]
Should we add it to the target? Should upstream have it in their aarch64 targets?

**Comment by pietroalbini** [comment]
If upstream is not passing the flag to LLD we should upstream it to add the flag by default. Also, as long as GCC 7.5.x implements the mitigation we should be good on that release, as we don't invoke LLD directly there.

**Comment by jonathanpallant** [comment]
```console
root@2e3b83479f59:/# aarch64-linux-gnu-gcc --fix-cortex-a53-843419

aarch64-linux-gnu-gcc: error: unrecognized command line option '--fix-cortex-a53-843419'; did you mean '-mfix-cortex-a53-843419'?
aarch64-linux-gnu-gcc: fatal error: no input files
compilation terminated.

root@2e3b83479f59:/# aarch64-linux-gnu-gcc -mfix-cortex-a53-843419

aarch64-linux-gnu-gcc: fatal error: no input files
compilation terminated.

root@2e3b83479f59:/# aarch64-linux-gnu-gcc -v

Using built-in specs.
COLLECT_GCC=aarch64-linux-gnu-gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc-cross/aarch64-linux-gnu/7/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=aarch64-linux-gnu --program-prefix=aarch64-linux-gnu- --includedir=/usr/aarch64-linux-gnu/include
Thread model: posix
gcc version 7.5.0 (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04)
root@2e3b83479f59:/#
```

**Comment by jonathanpallant** [comment]
We just need to turn them on :)

**Comment by jonathanpallant** [comment]
> Include detection in FST to require the flag to be passed if CC doesn't include it.

FST only checks targets which use a C compiler. As of this week the `aarch64-unknown-none` target now uses `rust-lld` directly, without using a C compiler. We can therefore add the flag to the target specification. This will then also be picked up by the `ferrocenetest` variant of the target, which does use GCC (although the GCC we use was going to add the flag anyway by default).

**Comment by jonathanpallant** [comment]
Safety manual changes: https://github.com/ferrocene/ferrocene/pull/133

**Comment by jonathanpallant** [comment]
Patch opened upstream: https://github.com/rust-lang/rust/pull/118095

**Comment by pietroalbini** [comment]
I think we should still have the test, to ensure the flag is passed to LLD (otherwise we could have every test passing if we forgot to pass the flag).

> I think the test has to be written in raw assembly.

Would sticking the related code in an `asm!()` block work?

**Comment by jonathanpallant** [comment]
Maybe? You have to ensure the bad instruction sits on a specific alignment (0x...FF8 or 0x...FFC) so you would need to control the alignment of the function and pads it with 1022 `nop` instructions. You then have to disassemble the binary the test compilation produces to check that either the veneer has been added or the bad instruction has been patched - it's not something you can easily check at runtime. Unless you transmute a function pointer to a `&[u32]` and disassemble it manually...

**Comment by pietroalbini** [comment]
I'm not sure how to handle the alignment of the function in Rust, but regarding the disassembly and checking, the `tests/assembly` suite has I think the same harness as the LLD test (see an example on https://github.com/ferrocene/ferrocene/blob/main/tests/assembly/slice-is_ascii.rs), so writing the test for it shouldn't be that hard. Not sure on the alignment though.

**Comment by jonathanpallant** [comment]
Well https://github.com/rust-lang/rust/issues/82232 would help. Maybe you can use `asm!(".align 4096")` inside a function?

**Comment by jonathanpallant** [comment]
```rust
#![feature(fn_align)]

extern "C" {
    fn puts(s: *const u8);
}

#[repr(align(4096))]
#[inline(never)]
pub fn test_function() {
    let message = b"hello\0";
    unsafe {
        puts(message.as_ptr());
    }
}

fn main() {
    test_function();
}
```

```console
$ objdump -t ./target/debug/aligntest | rustfilt | grep test_function
0000000100005000 l     F __TEXT,__text _aligntest::test_function
0000000100005000      d  *UND* _aligntest::test_function
```

Well that works.

**Comment by jonathanpallant** [comment]
Upstream changes were merged

**Comment by pietroalbini** [comment]
The only task here is writing a test that the mitigation is actually enabled.

**Comment by jonathanpallant** [comment]
> The only task here is writing a test that the mitigation is actually enabled.

Enabled in...

a) the rustc target definition, or
b) the ld.lld linker?

**Comment by jonathanpallant** [comment]
Some Rust:

```rust
#![no_std]
#![no_main]

use core::sync::atomic::AtomicU32;
use core::arch::asm;

static SOME_VALUE: AtomicU32 = AtomicU32::new(0);

#[no_mangle]
extern "C" fn _start() {
    // 1. An ADRP instruction, which writes to a register Rn.
    // 2. A load or store instruction which does not write to Rn
    // 3. <an optional additional instruction>
    // 4. A load or store (unsigned immediate) using Rn
    unsafe {
        asm!(
            "nop",
            "nop",
            "adrp x0, {global}",
            "ldr x1, [x1, #0]",
            "ldr x0, [x0, :lo12:{global}]",
            global = sym SOME_VALUE,
        );    
    }
}

#[panic_handler]
fn panic(_: &core::panic::PanicInfo) -> ! {
    loop {
        unsafe {
            core::arch::asm!("udf #0");
        }
    }
}
```

A linker script:

```text
/* RAM starts at 0x40000000 but if we ask to load the kernel there, QEMU will not load a DTB */

MEMORY {
    RAM : ORIGIN = 0xFF0, LENGTH = 4K
}

ENTRY(_start)
SECTIONS {
    .text : { *(.text .text*) } > RAM
    . = ALIGN(8);
    .data : { *(.data .data*) } > RAM
    . = ALIGN(8);
    .data : { *(.data .data*) } > RAM
    .bss : { *(.bss .bss* COMMON) } > RAM
    /DISCARD/ : {
        *(.note .note*)
    }
    . = ALIGN(8);
    . += 0x1000; /* 4kB of stack memory */
    stack_top = .;
}
```

Some output with or without the flag:

```text
Compiling...
Asm...
0000000000000ff0 <_start>:
     ff0:	d503201f 	nop
     ff4:	d503201f 	nop
     ff8:	b0000000 	adrp	x0, 1000 <_start+0x10>
     ffc:	f9400021 	ldr	x1, [x1]
    1000:	f9400400 	ldr	x0, [x0, #8]
    1004:	d65f03c0 	ret
Syms...

library:     file format elf64-littleaarch64

SYMBOL TABLE:
0000000000000000 l    df *ABS*	0000000000000000 library.5f8e040a67e0a7d4-cgu.0
0000000000001008 l     O .bss	0000000000000004 library::SOME_VALUE
0000000000000ff0 g     F .text	0000000000000018 _start
0000000000002010 g       .bss	0000000000000000 stack_top


Compiling (2)...
Asm (2)...
0000000000000ff0 <_start>:
     ff0:	d503201f 	nop
     ff4:	d503201f 	nop
     ff8:	b0000000 	adrp	x0, 1000 <_start+0x10>
     ffc:	f9400021 	ldr	x1, [x1]
    1000:	14000002 	b	1008 <__CortexA53843419_1000>
    1004:	d65f03c0 	ret

0000000000001008 <__CortexA53843419_1000>:
    1008:	f9400800 	ldr	x0, [x0, #16]
    100c:	17fffffe 	b	1004 <_start+0x14>
Syms (2)...

library:     file format elf64-littleaarch64

SYMBOL TABLE:
0000000000000000 l    df *ABS*	0000000000000000 library.5f8e040a67e0a7d4-cgu.0
0000000000001010 l     O .bss	0000000000000004 library::SOME_VALUE
0000000000001008 l     F .text	0000000000000008 __CortexA53843419_1000
0000000000000ff0 g     F .text	0000000000000018 _start
0000000000002018 g       .bss	0000000000000000 stack_top
```

**Comment by jonathanpallant** [comment]
The `ferrocene-self-test` tool will need access to a disassembler. How many of the LLVM tools do we build and bundle? 

Ah, there is an LLVM-tools bundle which includes `llvm-objdump`. I'm not sure how we'd make that a pre-requisite of ferrocene-self-test.

The other option is adding an ELF parser to the self test and walking the symbol table.

We are looking for a function called `__CortexA53843419_1000`, although I guess the name is subject to change, it won't change unless we update LLVM and if we update LLVM we should revisit the self-test to make sure it's all consistent.

**Comment by jonathanpallant** [comment]
Question for @pietroalbini:

> How many of the LLVM tools do we build and bundle?
